### PR TITLE
Fix maicos pipeline

### PR DESCRIPTION
**Pull request by hejamu**
The way we call our tests is now slightly different. This PR reflects this change.

### CODE REVIEW

**Review by IAlibay — APPROVED** [review]
thanks @hejamu !

**Comment by hejamu** [comment]
@IAlibay I forgot something important. We would now need two different commands for `latest` and `develop`, at least until a new tag is created... Is there a way neat to do that?

**Comment by IAlibay** [comment]
I am also a bit concerned that the `latest` run didn't actually throw an error even through the tests don't appear to have run. That's something to investigate separately.

**Comment by hejamu** [comment]
> I am also a bit concerned that the `latest` run didn't actually throw an error even through the tests don't appear to have run. That's something to investigate separately.

That it a weird tox thing, since the environment `tests` does not exist it just exists with exit code 0...

**Comment by PicoCentauri** [comment]
That is indeed weird. Also we have an additional check that should fail if the environment does not exist.

https://gitlab.com/maicos-devel/maicos/-/blob/main/tox.ini?ref_type=heads#L26-27

**Comment by PicoCentauri** [comment]
> @IAlibay I forgot something important. We would now need two different commands for latest and develop, at least until a new tag is created... Is there a neat way to do that?

We can also release a new version soonish. Maybe this is easier and we want to this in any case, right @hejamu 😉?

> I am also a bit concerned that the `latest` run didn't actually throw an error even through the tests don't appear to have run. That's something to investigate separately.

Seems like you can run `tox -e py39-tests` or `tox -e tests` successfully even though it is not specified explicitly in the config file. The [CI did this](https://github.com/MDAnalysis/MDAKits/actions/runs/6993042576/job/19025306445) and I was also able to run the tests successful with the current main `branch`.

**Comment by IAlibay** [comment]
@hejamu - it looks like things fixed themselves? (or at least CI started passing again). Is the change here still needed?

On my end I've not had the time to refactor the testing pipelines yet, I'll hopefully do so soon.

**Comment by IAlibay** [comment]
@hejamu since maicos had a release recently, this _should_ work?

I'll open a separate issue about allowing for separate develop/latest test requirements.

**Comment by hejamu** [comment]
Yes, this should not be a problem right now. We can close this PR.

**Comment by IAlibay** [comment]
@hejamu I think we have to merge this to fix the problem? (i.e. we shouldn't be calling py39-tests anymore it seems?). If you can update this branch I'm happy to merge this in.

**Review by IAlibay — APPROVED** [review]
LGTM - Thanks @hejamu!

**Pull request closed without merging**
