### PR TITLE
troubleshooting stub page

### PR DESCRIPTION
**Pull request by orbeckst**
As discussed at the last EOSS4/mdakits meeting: let's have a place in the docs where we can collect troubleshooting solutions and FAQ-style problems. This is just a stub.

### CODE REVIEW

**Comment by orbeckst** [comment]
sorry for the initial mess in commits, I branched from another old branch; I rebased against main and force pushed.

**Comment by IAlibay** [comment]
O.o is commit history broken somehow?  (P.S. I actually never know what causes this - I'd be keen to know if there's a simple fix I can tell folks to do when it happens)

**Comment by orbeckst** [comment]
No, it's fine. I was just on an old branch that had already been merged. This PR is now clean, it just looks horrible when you look at the commits above the force push.

**Review by fiona-naughton — APPROVED** [review]
lgtm - thanks for adding this @orbeckst !

**Pull request merged**
