### PR TITLE
Addition MDonatello to MDAKits

### PR DESCRIPTION
**Pull request by talagayev**
Addition of `MDonatello` to `MDAKits`:

- Package for 2D small molecule visualization for MDAnalysis, available at:
    - https://pypi.org/project/mdonatello/
    - https://anaconda.org/conda-forge/mdonatello

### CODE REVIEW

**Comment by talagayev** [comment]
The package would be ready to be reviewed :)
Currently the Package is sitting in my own Github repository without any Organizations or Communities connected to it, but it was part of GSOC 2024 with the project being:

https://summerofcode.withgoogle.com/programs/2024/projects/sfy3kuqc

So I am not sure if it should stay there. @richardjgowers, @yuxuanzhuang what are your opinons, should it be moved somewhere?

**Comment by orbeckst** [comment]
@richardjgowers @yuxuanzhuang have you discussed with @talagayev where the package should live? If it were to be moved then it would be nice to do that _before_ registering the kit, and so avoid having to re-review.

**Comment by richardjgowers** [comment]
@orbeckst We've not discussed but to me it makes sense for @talagayev to keep ownership of the repo

**Comment by talagayev** [comment]
I am fine with both of the solutions :) I think I have already the secret keys for Codecov and Docs implemented there, so it should be fine with the movement of the package, since I should be still able to commit changes if I move the package.

**Comment by IAlibay** [comment]
@lilyminium @fiona-naughton can either of you assign yourselves to shepherd this PR?

**Comment by fiona-naughton** [comment]
Looking good to me - thanks @talagayev! My one comment might be mention it's for use in jupyter notebooks in the description. 

I also see you have a CHANGELOG line, but it's commented out - is that intentional? No worries if you're planning to come back to it once the CHANGELOG has some entries, just wanted to check.

Leaving this for open for now since I'm not clear on if you were planning to move the repo under MDAnalysis or keep as-is?

(PS - love the logo :smile: )

**Comment by talagayev** [comment]
Hey @fiona-naughton, nice thank you :) I added the mention of jupyter notebook in the description.
I think I forgot to comment it out, but I adjusted it, just need to start using it, since there are currently no entries there :)

(PS. Thanks, hopefully I won't get a copyright strike for it :upside_down_face:  )

**Comment by fiona-naughton** [comment]
Sorry for the delay getting back to you @talagayev

Re: your logo, we've discussed amongst the coredevs. First, since this Kit isn't directly hosted with MDAnalysis, we're asking you to remove the MDAnalysis logo from your logo. You can still use the 'blank' MDAKits template (https://github.com/MDAnalysis/branding/tree/main/templates/MDAKits).

Second, please note that MDAnalysis does not endorse copyright infringement in any way. This is not a determination that your kit does or does not infringe any copyrights but a general statement of the position of the MDAnalysis organization. We recommend all authors check their kits use code and other materials under appropriate licenses and do not infringe on any copyrights. MDAnalysis cannot give any legal advice on these matters; if you're unsure about any legal matters please consult a lawyer.

Otherwise things are look good - thank you!

**Comment by talagayev** [comment]
> Sorry for the delay getting back to you @talagayev
> 
> Re: your logo, we've discussed amongst the coredevs. First, since this Kit isn't directly hosted with MDAnalysis, we're asking you to remove the MDAnalysis logo from your logo. You can still use the 'blank' MDAKits template (https://github.com/MDAnalysis/branding/tree/main/templates/MDAKits).
> 
> Second, please note that MDAnalysis does not endorse copyright infringement in any way. This is not a determination that your kit does or does not infringe any copyrights but a general statement of the position of the MDAnalysis organization. We recommend all authors check their kits use code and other materials under appropriate licenses and do not infringe on any copyrights. MDAnalysis cannot give any legal advice on these matters; if you're unsure about any legal matters please consult a lawyer.
> 
> Otherwise things are look good - thank you!

All good :)

Yup, I adjusted the Logo to the blank MDAKits Logo.

I removed also the additional Gear of the logo, so that it is now the blank MDAKits Logo, since yes it can be problematic, because of the copyright, so it makes sense to remove it :) I would add an additional gear if it would be fine, but I would do it by creating the gear design by myself, so that it won't be affected by copyrights. I woudl probably go for something to represent visualization/molecules so there won't be any indication of Donatello in the logo :)

Thank again for looking at the PR 😸

**Comment by talagayev** [comment]
> @talagayev you can use and re-use the MDAKit template (blank gears) — that's all covered by its license. Copying a gear and adding it is all fine. But the MDAnalysis logo (the blobs in three colors and the MDAnalysis word) can't be used for legal reasons.

Nice, then it should be fine as it is now on the readthedocs:

https://mdonatello.readthedocs.io/en/latest/

Should I modify something else for the MD? :)

**Comment by orbeckst** [comment]
@fiona-naughton can you review this kit or do you need reviewers?

**Comment by fiona-naughton** [comment]
Sorry for taking so long to get back to this @talagayev, but all looks good now, thanks - I'll go ahead and merge. Congrats on another MDAKit!

**Pull request merged**
