### PR TITLE
Add logos

### PR DESCRIPTION
**Pull request by lilyminium**
First attempt at adding logos. Is the favicon too blurry and hard to make out?

How should we license the logo as well? Are we happy with the same license as the MDAnalysis one?

I'll add the final SVGs and exports at different ppi to the branding repository, but just checking we don't want to make last minute changes.

Logo:

Screenshot 2024-06-16 at 7 02 00 pm

Favicon on dark:
Screenshot 2024-06-16 at 7 02 35 pm

Favicon on light:

Screenshot 2024-06-16 at 7 03 12 pm

### CODE REVIEW

**Comment by IAlibay** [comment]
Thanks, will look into this a bit more later - reminder for self, the logo is derivative of old logo, which means that we need to check the rules on licensing for derivatives, it at the very least likely inherits _something_ from the original license.

**Review by orbeckst — APPROVED** [review]
Looks fantastic. I am happy with it as is.

About license: NF is now holding the rights for the MDAnalysis logo but we can create derivatives for our own use. I will check with them how to change the license information https://github.com/MDAnalysis/branding/issues/6

For right now, we are safe by just not adding any license: @lilyminium is the author and used the MDA logo; as long as we don't provide a license, no-one can use it.

We are not applying this logo to kits (right??) so I think we are fine for right now. Please block if otherwise.

**Comment by orbeckst** [comment]
How about we use the empty gears as the default logo for kits?

**Review by IAlibay — APPROVED** [review]

**Comment by lilyminium** [comment]
`Error when evaluating 'strategy' for job 'mdakit-ci'. .github/workflows/gh-ci.yaml (Line: 64, Col: 17): Matrix vector 'mdakit' does not contain any values`

CI might be failing since this doesn't actually change any MDAKits.

**Comment by IAlibay** [comment]
> `Error when evaluating 'strategy' for job 'mdakit-ci'. .github/workflows/gh-ci.yaml (Line: 64, Col: 17): Matrix vector 'mdakit' does not contain any values`
> 
> CI might be failing since this doesn't actually change any MDAKits.

yeah that's an ok failing - not the issue we're seeing in cron.

**Comment by lilyminium** [comment]
Thanks for the reviews everyone!

**Comment by orbeckst** [comment]
Reading our trademark assignment contract, we are also assigning the rights to all new logos that we create for the project to NF so the MDAKits logo itself will also be governed by the same policies as the MDAnalysis logo itself.

I suggest we consider the "empty gears" a *template* and make that available under CC-BY or CC0.

**Comment by lilyminium** [comment]
Thanks @orbeckst! I'll likely be adding it to the cookiecutter-mdakit and branding repositories (first doing so in the cookiecutter here https://github.com/MDAnalysis/cookiecutter-mdakit/pull/120) instead of the MDAKits repo. I'll make clear that it's a template / placeholder, and add an additional license for it.

**Pull request merged**
