### PR TITLE
Feat : Add new logo for MDAkits

### PR DESCRIPTION
**Pull request by Satarupa22-SD**
@IAlibay @orbeckst This pr is regarding the new logo for MDAkits. I have added the draft and this can be change as per the preference of the community. I have not altered any other files as it's still up for discussion. Please do let me know your thoughts, thanks!

### CODE REVIEW

**Review by orbeckst — CHANGES_REQUESTED** [review]
I like the idea of having an MDAKits logo.

I don't know if @fiona-naughton was already working on one, though. If that's the case then we might close the PR.

In the meantime, here are a few comments. See also https://github.com/MDAnalysis/branding
- Do not rotate the MDAnalysis logo itself.
- MDAnalysis is typeset in ZAG Bold typeface.
- We write **MDAKit** and **MDAKits**, not ~~MDAnalysisKits~~.

As a simple variation of the standard logo you could use the default mdanalysis-logo from https://github.com/MDAnalysis/branding/tree/main/logos and add "MDAKits" below "MD//Analysis", similar to the logo for the [User Guide](https://userguide.mdanalysis.org/stable/index.html), [MDAnalysisData](https://www.mdanalysis.org/MDAnalysisData/), or alternatively look at [PMDA](https://www.mdanalysis.org/pmda/). 

Feel free to generate different logos and then we can decide what seems to capture MDAKits best.

Please note that logo creation is a bit of a complicated process and it is possible that we may decide that we don't like any suggestion.

**Comment by Satarupa22-SD** [comment]
@orbeckst thank you for reviewing my PR and explaining the guidelines. I will generate the new logo as directed by you.

**Comment by orbeckst** [comment]
@fiona-naughton @lilyminium @IAlibay do you have an idea what a MDAKits logo should look like?

@ianmkenney did you create something logo-like in your presentation, or some icons to represent MDAKits? I vaguely recall little boxes (like presents) or building blocks.

**Comment by orbeckst** [comment]
Hold off on doing more until we know that nobody else from our development team is already working on a logo.

(Just a general note: If you're creating a logo then you're really doing this more as a designer, so you should try to capture the essence of what an MDAKit is. Have a look at the paper https://doi.org/10.25080/gerudo-f2bc6f59-00a and everything else surrounding MDAKits. )

**Comment by ianmkenney** [comment]
@orbeckst is this what you're referring to?

mdakit

**Comment by Satarupa22-SD** [comment]
@orbeckst can you please take a look at [this](https://www.canva.com/design/DAF-QPkUSJY/9y_6024AQT31ig2uFzrLjQ/view?utm_content=DAF-QPkUSJY&utm_campaign=designshare&utm_medium=link&utm_source=editor). I am still working on adding the suitable font. Thank you for your time.

**Comment by Satarupa22-SD** [comment]
@orbeckst thank you for pointing that out. I have updated the link with a new logo. Please check slide 3,4. I have used the different tones of orange colour to design the box. I am still experiment, will also try with different colours on different sides.

**Comment by orbeckst** [comment]
Hello @Satarupa22-SD , thank you for your efforts here. We appreciate your initiative and drive to come up with a logo for MDAKits. After discussions with the development team we decided that we will handle branding including logos internally as this will allow us to better coordinate our overall branding strategy. Therefore, I will close this PR.

Sorry that it took a while to come to this conclusion. Thanks again for your work. I hope you will contribute in other ways to MDAnalysis.

**Comment by Satarupa22-SD** [comment]
@orbeckst sure :)

**Pull request closed without merging**
