### PR TITLE
updated pytim requirements

### PR DESCRIPTION
**Pull request by Marcello-Sega**
The latest version (1.0.2) adds compatibility with numpy2 and MDA 2.8, but requires now python>3.1 and mdanalysis >=2.8.0

### CODE REVIEW

**Comment by Marcello-Sega** [comment]
The test environment behave strangelyl; It [reports](https://github.com/MDAnalysis/MDAKits/actions/runs/12118640485/job/33783552144?pr=248#step:10:76) this errror:

```
=================================== FAILURES ===================================
______________ [doctest] pytim.observables.local_frame.Curvature _______________
168 
169         Example:
170 
171         >>> import MDAnalysis as mda
172         >>> import pytim
173         >>> from pytim.datafiles import WATER_GRO
174         >>> import numpy as np
175         >>> g=mda.Universe(WATER_GRO).select_atoms('name OW')
176         >>> inter = pytim.ITIM(g,molecular=False)
177         >>> curv = pytim.observables.Curvature().compute(g)
Expected nothing
Got:
    Warning: without having a PYTIM interface or passing
    a refgroup, the surface normal will be meaningless

```

while the actual docstring is different:

```python
"""
       >>> import MDAnalysis as mda
        >>> import pytim
        >>> from pytim.datafiles import WATER_GRO
        >>> import numpy as np
        >>> g=mda.Universe(WATER_GRO).select_atoms('name OW')
        >>> inter = pytim.ITIM(g,molecular=False)
        >>> curv = pytim.observables.Curvature().compute(g)
        >>> print(np.array_str((curv[:10,0]),precision=2,suppress_small=True))
        [-0.04 -0.17 -0.44 -0.15 -0.31  0.06  0.08 -0.22  0.08 -0.27]

"""
```
I added conda to my CI, and it passes with flying colors.

@IAlibay, could you help me having a look at this when/if you have time?

**Comment by Marcello-Sega** [comment]
For some reason, now the tests are passing. Maybe the environment got some update under the hood?

**Comment by Marcello-Sega** [comment]
@IAlibay, could you please review?

**Review by IAlibay — APPROVED** [review]
Thanks @Marcello-Sega apologies for the delayed review!

**Pull request merged**
