### PR TITLE
Adding mdaencore

### PR DESCRIPTION
**Pull request by ianmkenney**
Adding mdaencore. This kit moves the functionality of the MDAnalysis implementation of the ENCORE ensemble similarity analysis method out of the core core library.

### CODE REVIEW

**Comment by IAlibay** [comment]
@ianmkenney can you at least get a release out before we add this in?

**Comment by ianmkenney** [comment]
I already did

**Comment by IAlibay** [comment]
> I already did, https://github.com/MDAnalysis/mdaencore/releases/tag/0.1.0

Sorry I should have been clearer - a release out on PyPi.

**Review by IAlibay — APPROVED** [review]
Cheers

**Pull request merged**
