### PR TITLE
Adding PathSimAnalysis

### PR DESCRIPTION
**Pull request by ianmkenney**
Adding PathSimAnalysis to the MDAKits registry. This package computes the similarity between molecular dynamics trajectories using the Hausdorff or Fréchet distances.

@orbeckst would you like to be listed as a maintainer?

### CODE REVIEW

**Comment by orbeckst** [comment]
yes, makes sense

**Review by IAlibay — APPROVED** [review]
recipe looks fine to me, thanks

**Comment by lilyminium** [comment]
I can be a maintainer here too

**Comment by orbeckst** [comment]
This is one of the CZI EOSS4 milestones.

**Pull request merged**
